# Generated by Django 4.2.16 on 2024-10-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanza_nr', models.IntegerField()),
                ('stanza_rn', models.CharField(default='', max_length=8)),
                ('stanza_tx', models.TextField(default='')),
                ('pic_file', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
