# Generated by Django 4.2.16 on 2024-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanza',
            name='pic_file',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stanza',
            name='stanza_rn',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stanza',
            name='stanza_tx',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
