# Generated by Django 4.2.16 on 2024-10-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_app', '0002_alter_stanza_pic_file_alter_stanza_stanza_rn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanza',
            name='pic_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stanza',
            name='pic_v',
            field=models.IntegerField(default=0),
        ),
    ]
