# Generated by Django 4.2.16 on 2024-10-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('O_app', '0003_stanza_pic_h_stanza_pic_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanza',
            name='stanza_rn',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
